language: node_js
node_js:
  - "node"
install:
  - yarn install
script:
  - yarn test
cache:
  yarn: true
after_success: yarn jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: "mohsen.31369@gmail.com"
  api_key: $npm_api_key
  skip_cleanup: true
  on:
    tags: true
