language: node_js
node_js:
  - "node"
install:
  - yarn install
script:
  - yarn test
branches:
  only:
    - master
cache:
  yarn: true
deploy:
  provider: npm
  email: "mohsen.31369@gmail.com"
  api_key: $npm_api_key
  on:
    tags: true
